### ISSUE TITLE
Adicionar exemplos práticos

### ISSUE THREAD

**Issue by jardelima** [FalaAiMatheus/card-flag#1]
Percebi que não tem exemplos práticos de como aplicar a lib. Adicionando isso acho que fica bem legal. Pode adicionar exemplos de em quais campos adicionar a lib (inputs, divs...), como implementar, etc. 
Projeto bacana, já sofri pra encontrar uma lib assim que realmente funcionasse. :joy:

**Comment by FalaAiMatheus** [comment]
Valeu Jardel pela dica!

Já adicionei uma pasta chamada #._examples, nela vai conter alguns exemplos de codigo que estão desenvolvidos dentro da biblioteca.

Inicialmente ela está em português, mas pra frente pretendo ter uma versão em inglês.
